USE airlinedb;

-- 1.FIND THE ABBREVIATION OF FLIGHTS 3 CHARACTERS LONG LAST

SELECT abbreviation, RIGHT(abbreviation,3) AS LAST_THREEE_CHAR FROM airlines;

-- 2. FIND THE ABBREVIATION OF FLIGHTS 3 CHARACTERS FORM STARTING 

SELECT abbreviation, LEFT(abbreviation,3) AS FIRST_THREE_CHAR FROM airlines;

-- 3.REMOVE THE 'IR' FROM ALL THE ABBREVIATION OF FLIGHTS

SELECT abbreviation, TRIM('ir' FROM abbreviation) AS REMOVE_IR FROM airlines;

-- 4. FIND THE LOCATION ON 'I' ABBREVIATION OF FLIGHTS

SELECT abbreviation, POSITION('i' IN abbreviation) AS POSITION_I FROM airlineS;

-- 5. GET THE SUB STRING OF INDEX 4 TO 2 CHARACTERS FROM ABBREVIATION OF ALL THE FLIGHTS

SELECT abbreviation, SUBSTR(abbreviation,4,2) AS SUBS_STRING FROM airlines;

-- 6. FIND THE COUNT OF ALL FLIGHTS FOR AIRLINES AND MAKE AVERAGE OF THAT

SELECT AVG(air)
FROM
(SELECT COUNT(Airline) as air
FROM flights
group by airline)
airline_table;

